spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/operatorDB
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  config:
    ussd-url: http://localhost:8333/api/v1/ussd

server:
  port: 7008